[env]
CC_aarch64-unknown-linux-gnu = "aarch64-linux-gnu-gcc"
CC_aarch64-unknown-linux-musl = "aarch64-linux-gnu-gcc"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
rustflags = ["-C", "target-feature=+mte"]

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-gnu-gcc"
