[package]
name = "wasmtime-c-api-macros"
version = "0.0.0"
authors = ["The Wasmtime Project Developers"]
license = "Apache-2.0 WITH LLVM-exception"
edition.workspace = true
publish = false

[lib]
proc-macro = true
test = false
doctest = false

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"
