(module
  (memory 1 1)
  (func (export "sign") (param i64) (result i64)
        (i64.pointer_sign (local.get 0) (i64.const 0))
        (return)
  )
  (func (export "strip") (param i64) (result i64)
        (i64.pointer_strip (local.get 0))
        (return)
  )
  (func (export "sign+auth") (param i64) (param i64) (result i64)
        (i64.pointer_sign (local.get 0) (i64.const 0))
        (local.get 1)
        (i64.add)
        (i64.const 0)
        (i64.pointer_auth)
        (return)
  )
)
