(module
  (memory 1 1)
  (global $sp (mut i32) (i32.const 64))
  (func (export "foo") (param $idx i64) (result i32)
    (local $ptr i64)
    (i32.const 0)
    (i32.const 16)
    (segment.stack_new)
    (local.tee $ptr)
    (local.get $idx)
    (i64.const 2)
    (i64.shl)
    (i64.add)
    (i32.const 42)
    (i32.store_segment)
    (local.get $ptr)
    (local.get $idx)
    (i64.const 2)
    (i64.shl)
    (i64.add)
    (i32.load_segment)
    (local.get $ptr)
    (i32.const 16)
    (segment.free)
    (return)
  )
)
