(module
  (memory i64 1 1)
  (func (export "foo") (param $idx i64) (result i32)
    (local $ptr i64)
    (i64.const 0)
    (i64.const 16)
    (segment.stack_new)
    (local.tee $ptr)
    (local.get $idx)
    (i64.const 2)
    (i64.shl)
    (i64.add)
    (i32.const 42)
    (i32.store)
    (local.get $ptr)
    (local.get $idx)
    (i64.const 2)
    (i64.shl)
    (i64.add)
    (i32.load)
    (local.get $ptr)
    (i64.const 16)
    (segment.free)
    (return)
  )
)
